AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  slidenotes-backend

  Sample SAM Template for slidenotes-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: false
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  submitRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: submitRequest/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          PPTX_SQS_QUEUE: !Ref pptxToTextQueue
          PDF_SQS_QUEUE: !Ref pdfToTextQueue
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
          DYNAMODB_TABLE_USERS: !Ref usersDynamoDB
      Events:
        submitRequest:
          Type: Api 
          Properties:
            Path: /submitRequest
            Method: POST
            RestApiId:
              Ref: slidenotesApi 
      Policies:
        - AmazonSQSFullAccess
        - AmazonDynamoDBFullAccess
       
  checkRequestStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: checkRequestStatus/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
      Events:
        checkRequestStatus:
          Type: Api 
          Properties:
            Path: /checkRequestStatus
            Method: POST
            RestApiId:
              Ref: slidenotesApi
      Policies:
        - AmazonDynamoDBFullAccess

  getUserNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getUserNotes/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
          DYNAMODB_TABLE_USERS: !Ref usersDynamoDB
      Events:
        checkRequestStatus:
          Type: Api 
          Properties:
            Path: /getUserNotes
            Method: POST
            RestApiId:
              Ref: slidenotesApi
      Policies:
        - AmazonDynamoDBFullAccess

  getNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getNotes/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
      Events:
        checkRequestStatus:
          Type: Api 
          Properties:
            Path: /getNotes
            Method: POST
            RestApiId:
              Ref: slidenotesApi
      Policies:
        - AmazonDynamoDBFullAccess

  stripeWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stripeWebhook/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref usersDynamoDB
      Events:
        createStripeCheckoutSession:
          Type: Api 
          Properties:
            Path: /stripeWebhook
            Method: POST
            RestApiId:
              Ref: slidenotesApi
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:StripeTestKeys-Ct4u4T"

  createStripeCheckoutSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createStripeCheckoutSession/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref usersDynamoDB
      Events:
        createStripeCheckoutSession:
          Type: Api 
          Properties:
            Path: /createStripeCheckoutSession
            Method: POST
            RestApiId:
              Ref: slidenotesApi
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:StripeTestKeys-Ct4u4T"

  createStripePortalSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createStripePortalSession/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref usersDynamoDB
      Events:
        createStripePortalSession:
          Type: Api 
          Properties:
            Path: /createStripePortalSession
            Method: POST
            RestApiId:
              Ref: slidenotesApi
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:StripeTestKeys-Ct4u4T"

  convertPPTXToTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1024
      CodeUri: convertPPTXToText/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          S3_BUCKET: !Ref pptxBucket
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
          SQS_QUEUE: !Ref summarizeTextQueue 
      Events:
        convertPPTXToTextQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt pptxToTextQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess

  convertPDFToTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1024
      CodeUri: convertPDFToText/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          S3_BUCKET: !Ref pptxBucket
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
          SQS_QUEUE: !Ref summarizeTextQueue 
      Events:
        convertPPTXToTextQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt pdfToTextQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess

  summarizeTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1024
      CodeUri: summarizeText/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - x86_64 
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
          S3_BUCKET: !Ref pptxBucket
      Events:
        summarizeTextQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt summarizeTextQueue.Arn
            BatchSize: 1
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:OpenAIKey-sXAkvm"

  downloadNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: downloadNotes/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref slidenotesDynamoDB
      Events:
        downloadNotes:
          Type: Api 
          Properties:
            Path: /downloadNotes
            Method: POST
            RestApiId:
              Ref: slidenotesApi 
      Policies:
        - AmazonDynamoDBFullAccess
  
  sendPhoneCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sendPhoneCode/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref usersDynamoDB
      Events:
        sendPhoneCode:
          Type: Api 
          Properties:
            Path: /sendPhoneCode
            Method: POST
            RestApiId:
              Ref: slidenotesApi 
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:TwilioKeys-A75GIG"
  
  checkPhoneCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: checkPhoneCode/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
      - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref usersDynamoDB
      Events:
        checkPhoneCode:
          Type: Api 
          Properties:
            Path: /checkPhoneCode
            Method: POST
            RestApiId:
              Ref: slidenotesApi 
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:TwilioKeys-A75GIG"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:us-west-2:586103959850:secret:StripeTestKeys-Ct4u4T"
  
  slidenotesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  pptxBucket:
    Type: AWS::S3::Bucket

  pptxToTextQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  pdfToTextQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  summarizeTextQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  slidenotesDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: raw_text_hash
          AttributeType: S
        - AttributeName: timeCreated
          AttributeType: N
        - AttributeName: phoneNumberHash
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: raw_text_cache_hash
          KeySchema:
          - AttributeName: raw_text_hash
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - notes_text
            - premium
            - currentStatus
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: phoneNumberHashIndex
          KeySchema:
          - AttributeName: phoneNumberHash
            KeyType: HASH
          - AttributeName: timeCreated 
            KeyType: RANGE
          Projection:
            NonKeyAttributes:
            - id
            - s3key
            - premium
            - currentStatus
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  usersDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: phoneNumberHash
          AttributeType: S
        - AttributeName: stripeId
          AttributeType: S
      KeySchema:
        - AttributeName: phoneNumberHash
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: stripeIdIndex
          KeySchema:
          - AttributeName: stripeId
            KeyType: HASH
          Projection:
            NonKeyAttributes:
            - premiumPaidTime 
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  slidenotesApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${slidenotesApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/
